Repository niwanetwork/niwa-website, pull requests merged in 2021-07, with the labels that each got.

#54 Revamped homepage
  dependencies/jquery/jquery-1.11.0.min.js
  dependencies/jquery/jquery-migrate-1.2.1.min.js
  dependencies/slick/ajax-loader.gif
  dependencies/slick/fonts/slick.eot
  dependencies/slick/fonts/slick.svg
  dependencies/slick/fonts/slick.ttf
  dependencies/slick/fonts/slick.woff
  dependencies/slick/slick-theme.css
  dependencies/slick/slick.css
  dependencies/slick/slick.min.js
  index.php
  style.css
Labels: enhancement

#53 Adding Discord widget to sidebar
  _sidebar.php
  style.css
Labels: enhancement

#55 New affiliates page
  _api.php
  _menu.php
  _sidebar.php
  affiliates.php
  data/affiliates.json
  images/logos/bulbagarden.png
  images/logos/doomwiki.png
  images/logos/halopedia.png
  images/logos/jojo.png
  images/logos/khwiki.png
  images/logos/seiwa.png
  images/logos/wikifang.png
  images/logos/wikimon.png
  images/logos/wikisimpsons.png
  images/logos/zeldachaos.png
  members.php
Labels: enhancement

#63 Use labels for contact form, refactor styling
  contact.php
  style.css
Labels: bug, enhancement

#40 Removing outdated statements/correcting some grammar and wording
  data/members.json
Labels: enhancement

#68 Updating Xeno Series Wiki logo
  images/logos/xenoserieswiki.png
Labels: enhancement

#69 Carousel fixes
  index.php
  style.css
Labels: bug

#71 Update members.json
  data/members.json
Labels: enhancement
